name: mas_labs
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Kiria-F/dart-mas-lab

environment:
  sdk: ^3.5.3

dependencies:
  grpc: ^4.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
